[project]
name = "wordle-solves"
version = "0.1.0"
description = "A repository containing a bunch of ways of solving the popular game Wordle."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
]
